spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 100
        default-page-size: 1
      sort:
        sort-parameter: id