spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public